Repository Chartes-TNAH/prosopochartes, pull requests merged in 2019-03, with the labels that each got.

#5 Création de l'architecture de l'application
  .DS_Store
  .idea/libraries/R_User_Library.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/prosopochartes.iml
  .idea/vcs.xml
  .idea/workspace.xml
  prosopapp/.DS_Store
  prosopapp/.flaskenv
  prosopapp/app.py
  prosopapp/app/.DS_Store
  prosopapp/app/__init__.py
  prosopapp/app/routes.py
  prosopapp/app/statics/.DS_Store
  prosopapp/app/statics/bootstrap/.DS_Store
  prosopapp/app/statics/bootstrap/css/bootstrap-grid.css
  prosopapp/app/statics/bootstrap/css/bootstrap-grid.css.map
  prosopapp/app/statics/bootstrap/css/bootstrap-grid.min.css
  prosopapp/app/statics/bootstrap/css/bootstrap-grid.min.css.map
  prosopapp/app/statics/bootstrap/css/bootstrap-reboot.css
  prosopapp/app/statics/bootstrap/css/bootstrap-reboot.css.map
  prosopapp/app/statics/bootstrap/css/bootstrap-reboot.min.css
  prosopapp/app/statics/bootstrap/css/bootstrap-reboot.min.css.map
  prosopapp/app/statics/bootstrap/css/bootstrap.css
  prosopapp/app/statics/bootstrap/css/bootstrap.css.map
  prosopapp/app/statics/bootstrap/css/bootstrap.min.css
  prosopapp/app/statics/bootstrap/css/bootstrap.min.css.map
  prosopapp/app/statics/bootstrap/js/bootstrap.bundle.js
  prosopapp/app/statics/bootstrap/js/bootstrap.bundle.js.map
  prosopapp/app/statics/bootstrap/js/bootstrap.bundle.min.js
  prosopapp/app/statics/bootstrap/js/bootstrap.bundle.min.js.map
  prosopapp/app/statics/bootstrap/js/bootstrap.js
  prosopapp/app/statics/bootstrap/js/bootstrap.js.map
  prosopapp/app/statics/bootstrap/js/bootstrap.min.js
  prosopapp/app/statics/bootstrap/js/bootstrap.min.js.map
  prosopapp/app/templates/.DS_Store
  prosopapp/app/templates/headerfooter.html
  prosopapp/app/templates/pages/accueil.html
  prosopapp/app/templates/pages/chercheurs.html
  prosopapp/app/templates/pages/noticechercheur
  prosopapp/app/templates/pages/recherche.html
  prosopapp/app/templates/pages/resultats.html
  prosopapp/prosopochartes.sqlite
  requirements.txt
Labels: enhancement

#9 Changement d'architecture et correction des bugs
  .idea/workspace.xml
  prosopapp/.flaskenv
  prosopapp/app.py
  prosopapp/app/__init__.py
  prosopapp/app/app.py
  prosopapp/app/routes.py
  prosopapp/run.py
Labels: enhancement

#13 Ajout de la barre de navigation
  prosopapp/app/app.py
  prosopapp/app/routes.py
  prosopapp/app/statics/Images/ENC.jpg
  prosopapp/app/statics/Images/EcoleChartes.png
  prosopapp/app/templates/headerfooter.html
  prosopapp/app/templates/headerfooter_test.html
  prosopapp/app/templates/pages/accueil.html
  prosopapp/app/templates/pages/chercheurs.html
  prosopapp/app/templates/pages/noticechercheur.html
  prosopapp/app/templates/pages/recherche.html
  prosopapp/app/templates/pages/resultats.html
  prosopapp/app/templates/partials/css.html
  prosopapp/app/templates/partials/metadata.html
Labels: enhancement

#16 Modification du Master
  .idea/codeStyles/Project.xml
  .idea/encodings.xml
  .idea/libraries/R_User_Library.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/prosopochartes.iml
  .idea/vcs.xml
  .idea/workspace.xml
  README.md
  comptes_rendus_seances/2019-03-05.md
  pas_a_pas_github.md
  prosopapp/.idea/codeStyles/Project.xml
  prosopapp/.idea/dbnavigator.xml
  prosopapp/.idea/encodings.xml
  prosopapp/.idea/misc.xml
  prosopapp/.idea/modules.xml
  prosopapp/.idea/prosopapp.iml
  prosopapp/.idea/vcs.xml
  prosopapp/.idea/workspace.xml
  prosopapp/app/app.py
  prosopapp/app/modeles/__init__.py
  prosopapp/app/modeles/donnees.py
  prosopapp/app/routes.py
  prosopapp/app/statics/Images/ENC.jpg
  prosopapp/app/statics/Images/EcoleChartes.png
  prosopapp/app/templates/headerfooter.html
  prosopapp/app/templates/headerfooter_test.html
  prosopapp/app/templates/pages/accueil.html
  prosopapp/app/templates/pages/chercheurs.html
  prosopapp/app/templates/pages/noticechercheur.html
  prosopapp/app/templates/pages/recherche.html
  prosopapp/app/templates/pages/resultats.html
  prosopapp/app/templates/partials/css.html
  prosopapp/app/templates/partials/metadata.html
Labels: Master

#18 Corrections db et instanciation des classes
  .DS_Store
  prosopapp/app/modeles/donnees.py
  prosopapp/app/routes.py
Labels: DB

#19 Ld headerfooter liens
  prosopapp/app/routes.py
  prosopapp/app/templates/headerfooter.html
  prosopapp/app/templates/headerfooter_test.html
  prosopapp/app/templates/pages/accueil.html
  prosopapp/app/templates/pages/chercheurs.html
  prosopapp/app/templates/pages/noticechercheur.html
  prosopapp/app/templates/pages/recherche.html
  prosopapp/app/templates/pages/resultats.html
Labels: enhancement

#22 Ajout des modifications sur la page chercheurs
  prosopapp/app/routes.py
  prosopapp/app/statics/Images/anonyme.jpg
  prosopapp/app/templates/pages/chercheurs.html
Labels: Chercheurs

#23 Modification routes relatives, def fonction chercheurs, app.py
  prosopapp/app/app.py
  prosopapp/app/modeles/donnees.py
  prosopapp/app/routes.py
  prosopapp/app/templates/pages/chercheurs.html
  prosopapp/prosopochartes.sqlite
Labels: enhancement

#24 Modifs Recherche plein texte
  prosopapp/app/routes.py
  prosopapp/app/templates/headerfooter.html
  prosopapp/app/templates/pages/resultats.html
Labels: enhancement

#26 Mise en forme finale de la page chercheurs
  prosopapp/app/routes.py
  prosopapp/app/templates/pages/chercheurs.html
Labels: Chercheurs

#27 Lien url_for de chercheurs à noticechercheur
  prosopapp/app/routes.py
  prosopapp/app/templates/pages/chercheurs.html
  prosopapp/app/templates/pages/noticechercheur.html
  prosopapp/app/templates/pages/resultats.html
Labels: Chercheurs

#28 Correction d'erreurs de typage dans la base de données et dans les modèles + modification de la configuration de l'app
  prosopapp/.flaskenv
  prosopapp/app/app.py
  prosopapp/app/modeles/donnees.py
  prosopapp/prosopochartes.sqlite
Labels: enhancement

#29 Ajout des pages notices chercheurs et résolution des images vides
  prosopapp/app/routes.py
  prosopapp/app/statics/Images/.DS_Store
  prosopapp/app/statics/Images/ENC_Logo.png
  prosopapp/app/statics/Images/anonyme.jpg
  prosopapp/app/statics/Images/anonyme3.jpg
  prosopapp/app/templates/pages/accueil.html
  prosopapp/app/templates/pages/chercheurs.html
  prosopapp/app/templates/pages/noticechercheur.html
Labels: Chercheurs

#31 Ajout des values dans les balises <select> du template recherche
  prosopapp/app/templates/pages/recherche.html
Labels: Templates

#32 Modification de la page recherche.html
  prosopapp/app/templates/pages/recherche.html
Labels: formulaire

#33 Modification de l'affichage des pages chercheurs et accueil
  prosopapp/.flaskenv
  prosopapp/app/app.py
  prosopapp/app/routes.py
  prosopapp/app/statics/Images/anonyme2.jpg
  prosopapp/app/statics/Images/anonyme3.jpg
  prosopapp/app/templates/pages/accueil.html
  prosopapp/app/templates/pages/chercheurs.html
  prosopapp/app/templates/pages/noticechercheur.html
  prosopapp/run.py
Labels: Chercheurs

#35 Ajout de la pagination
  prosopapp/app/app.py
  prosopapp/app/constantes.py
  prosopapp/app/routes.py
  prosopapp/app/templates/pages/resultats.html
Labels: Pagination

#37 Modifications relatives aux templates
  prosopapp/app/routes.py
  prosopapp/app/statics/Images/logochartes.jpg
  prosopapp/app/templates/headerfooter.html
  prosopapp/app/templates/pages/accueil.html
  prosopapp/app/templates/pages/chercheurs.html
  prosopapp/app/templates/pages/noticechercheur.html
  prosopapp/app/templates/pages/resultats.html
  prosopapp/app/templates/pages/resultats_avances.html
Labels: Templates

#38 Ajout de la barre de recherche rapide sur le formulaire de recherche avancé
  prosopapp/app/routes.py
  prosopapp/app/templates/pages/recherche.html
Labels: formulaire

#39 Résolutions des bugs de .paginate
  .DS_Store
  prosopapp/app/routes.py
  prosopapp/app/templates/pages/resultats.html
  prosopapp/app/templates/pages/resultats_avances.html
Labels: Pagination

#40 Modifications de la page d'accueil et commentaire de la fonction resultats()
  prosopapp/app/routes.py
  prosopapp/app/statics/Images/carousel1.png
  prosopapp/app/statics/Images/carousel2.png
  prosopapp/app/statics/Images/carousel3.png
  prosopapp/app/templates/pages/accueil.html
Labels: Compréhension du code, Templates

#41 Requêtes dans les drops-downs pour la recherche avancée
  prosopapp/app/routes.py
  prosopapp/app/templates/pages/recherche.html
  prosopapp/app/templates/pages/resultats_avances.html
Labels: bug, formulaire

#43 Correction du bug lié à la recherche avancée
  prosopapp/app/routes.py
  prosopapp/app/templates/pages/recherche.html
  prosopapp/app/templates/pages/resultats_avances.html
Labels: formulaire

#44 Issue #42 : Modification de la base de données (ajout d'une relation many to many)
  prosopapp/prosopochartes.sqlite
Labels: DB

#45 Issue #42 : Modification du fichier donnees.py (ajout d'une relation many to many)
  prosopapp/app/modeles/donnees.py
  prosopapp/app/routes.py
Labels: DB, enhancement

#46 Correction du fichier donnees.py
  prosopapp/app/modeles/donnees.py
Labels: DB

#48 Modification donnes et mises à jours des pages recherches et noticesch. + tests requêtes
  prosopapp/app/modeles/donnees.py
  prosopapp/app/routes.py
  prosopapp/app/templates/pages/chercheurs.html
  prosopapp/app/templates/pages/noticechercheur.html
Labels: Chercheurs, DB, formulaire

#49 Mise à jour des champs de formulaire requête all et requête avancée
  prosopapp/app/app.py
  prosopapp/app/modeles/donnees.py
  prosopapp/app/routes.py
  prosopapp/app/templates/pages/chercheurs.html
  prosopapp/app/templates/pages/noticechercheur.html
Labels: formulaire

#50 Brève correction du fichier recherche.html
  base_sqlite/prosopochartes.sqlite
  prosopapp/app/templates/pages/recherche.html
Labels: DB, formulaire

#53 Messages erreurs : modifications de routes.py et resultats_avances.html
  prosopapp/app/routes.py
  prosopapp/app/templates/pages/resultats_avances.html
Labels: enhancement, formulaire

#52 Définition d'un secret_key
  prosopapp/app/app.py
Labels: enhancement

#54 Fonction resultats_avances : ajout messages erreurs
  prosopapp/app/routes.py
Labels: enhancement, formulaire

#55 Simplification de la fonction resultats_avances
  prosopapp/app/routes.py
Labels: formulaire

#56 Corrections diverses
  prosopapp/app/app.py
  prosopapp/app/modeles/donnees.py
  prosopapp/app/routes.py
  prosopapp/app/templates/pages/chercheurs.html
  prosopapp/app/templates/pages/noticechercheur.html
  prosopapp/app/templates/pages/recherche.html
  prosopapp/app/templates/pages/resultats.html
  prosopapp/app/templates/pages/resultats_avances.html
Labels: Compréhension du code, formulaire

#58 Ajout du compte-rendu
  Compte_rendu_final_projet_python.md
Labels: Documentation

#60 Classement des résultats de la recherche avancée
  prosopapp/app/routes.py
  prosopapp/app/templates/headerfooter.html
  prosopapp/app/templates/pages/accueil.html
  prosopapp/app/templates/pages/chercheurs.html
  prosopapp/app/templates/pages/recherche.html
  prosopapp/app/templates/pages/resultats_avances.html
  prosopapp/app/templates/pages/telechargement.html
Labels: enhancement, formulaire

#62 Corrections diverses
  base_csv/Répartition.csv
  base_sqlite/prosopochartes.sqlite
  prosopapp/app/app.py
  prosopapp/app/errorhandler.py
  prosopapp/app/routes.py
  prosopapp/app/templates/headerfooter.html
  prosopapp/app/templates/pages/chercheurs.html
  prosopapp/app/templates/pages/noticechercheur.html
  prosopapp/prosopochartes.sqlite
Labels: DB, errors

#63 Notice aléatoire
  prosopapp/app/routes.py
  prosopapp/app/templates/headerfooter.html
  prosopapp/app/templates/pages/accueil.html
  prosopapp/app/templates/pages/noticechercheur.html
Labels: enhancement

#65 Fusion
  base_csv/Répartition.csv
  base_sqlite/prosopochartes.sqlite
  prosopapp/app/app.py
  prosopapp/app/errorhandler.py
  prosopapp/app/routes.py
  prosopapp/app/templates/headerfooter.html
  prosopapp/app/templates/pages/accueil.html
  prosopapp/app/templates/pages/chercheurs.html
  prosopapp/app/templates/pages/erreurs/404.html
  prosopapp/app/templates/pages/erreurs/410.html
  prosopapp/app/templates/pages/erreurs/500.html
  prosopapp/app/templates/pages/noticechercheur.html
  prosopapp/app/templates/pages/recherche.html
  prosopapp/app/templates/pages/resultats_avances.html
  prosopapp/app/templates/pages/telechargement.html
  prosopapp/prosopochartes.sqlite
Labels: Master
